# Image Handling

In [229]:
import os
import cv2 
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score

In [230]:
os.getcwd()

'C:\\Users\\Manisha\\DATA SCIENCE\\MACHINE LEARNING\\Dog breeds\\dataset\\Yorkshire_Terrier'

## 1. Beagle

In [231]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Beagle")

In [232]:
os.listdir()

['Beagle_37.jpg',
 'Beagle_38.jpg',
 'Beagle_39.jpg',
 'Beagle_4.jpg',
 'Beagle_40.jpg',
 'Beagle_41.jpg',
 'Beagle_42.jpg',
 'Beagle_43.jpg',
 'Beagle_44.jpg',
 'Beagle_45.jpg',
 'Beagle_46.jpg',
 'Beagle_47.jpg',
 'Beagle_48.jpg',
 'Beagle_49.jpg',
 'Beagle_5.jpg',
 'Beagle_50.jpg',
 'Beagle_51.jpg',
 'Beagle_52.jpg',
 'Beagle_53.jpg',
 'Beagle_54.jpg',
 'Beagle_55.jpg',
 'Beagle_56.jpg',
 'Beagle_57.jpg',
 'Beagle_58.jpg',
 'Beagle_59.jpg',
 'Beagle_6.jpg',
 'Beagle_60.jpg',
 'Beagle_61.jpg',
 'Beagle_62.jpg',
 'Beagle_63.jpg',
 'Beagle_64.jpg',
 'Beagle_65.jpg',
 'Beagle_66.jpg',
 'Beagle_67.jpg',
 'Beagle_68.jpg',
 'Beagle_69.jpg',
 'Beagle_7.jpg',
 'Beagle_70.jpg',
 'Beagle_71.jpg',
 'Beagle_72.jpg',
 'Beagle_73.jpg',
 'Beagle_74.jpg',
 'Beagle_75.jpg',
 'Beagle_76.jpg',
 'Beagle_77.jpg',
 'Beagle_78.jpg',
 'Beagle_79.jpg',
 'Beagle_8.jpg',
 'Beagle_80.jpg',
 'Beagle_81.jpg',
 'Beagle_82.jpg',
 'Beagle_83.jpg',
 'Beagle_84.jpg',
 'Beagle_85.jpg',
 'Beagle_86.jpg',
 'Beagle_87.jpg',
 'Beagle_88.jpg',
 'Beagle_89.jpg',
 'Beagle_9.jpg',
 'Beagle_90.jpg',
 'Beagle_91.jpg',
 'Beagle_92.jpg',
 'Beagle_93.jpg',
 'Beagle_94.jpg',
 'Beagle_95.jpg',
 'Beagle_96.jpg',
 'Beagle_97.jpg',
 'Beagle_98.jpg',
 'Beagle_99.jpg']

In [233]:
len(os.listdir())

69

In [234]:
# Reading a Single image
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Beagle\Beagle_54.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [235]:
# Reading All the images
images = []
for image in os.listdir():
    arr = cv2.imread(image) 
    res = cv2.resize(arr,(150,150)) # 3d arrays (150 * 150 * 3)
    flat = res.flatten()
    images.append(flat)
# Displaying all the images    
    cv2.imshow('img',arr)
    cv2.waitKey(5000)
    cv2.destroyAllWindows()

In [11]:
res

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]], dtype=uint8)

In [12]:
len(images)

69

### Creating the DataFrame

In [13]:
beagle = pd.DataFrame(images)
beagle['Breed'] = 'Beagle'

In [14]:
beagle.duplicated().sum()

48

In [15]:
beagle = beagle.drop_duplicates()

In [16]:
len(beagle)

21

In [17]:
beagle.duplicated().sum()

0

In [18]:
beagle

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,201,178,186,199,181,188,187,174,180,157,...,147,156,169,143,152,163,145,152,161,Beagle
1,17,41,41,21,45,45,25,51,51,27,...,33,163,152,35,166,155,39,170,159,Beagle
2,157,189,202,157,189,202,157,189,202,157,...,2,20,49,2,19,47,2,19,46,Beagle
3,67,120,117,69,122,119,71,124,121,73,...,74,126,119,52,100,96,36,81,78,Beagle
4,218,226,226,219,227,227,222,231,231,222,...,10,11,15,2,1,10,0,1,11,Beagle
5,204,182,171,204,182,171,204,182,171,204,...,215,195,194,211,188,188,211,187,187,Beagle
6,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,Beagle
7,0,1,0,0,2,0,1,6,4,6,...,107,120,142,109,122,144,109,122,144,Beagle
8,200,190,183,230,220,213,208,198,191,229,...,142,140,129,157,154,142,152,149,135,Beagle
9,129,125,107,129,125,107,129,125,107,129,...,85,83,65,89,85,68,90,86,68,Beagle
11,43,68,70,44,69,71,46,70,70,45,...,73,157,93,72,153,90,72,153,90,Beagle
12,192,218,230,187,213,225,180,206,218,177,...,130,138,155,105,114,127,97,108,116,Beagle
13,198,192,193,198,192,193,199,193,194,199,...,62,71,78,64,76,80,65,77,81,Beagle
15,71,148,140,75,151,144,84,157,149,91,...,52,153,118,50,147,115,52,146,115,Beagle
16,9,18,15,9,18,15,6,17,14,6,...,71,201,194,70,199,194,68,200,194,Beagle
17,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Beagle
18,221,215,220,222,216,221,225,218,223,227,...,57,100,87,46,92,83,43,92,84,Beagle
19,148,154,159,147,153,158,148,154,159,154,...,131,136,134,130,134,133,128,133,131,Beagle
20,79,80,84,84,85,89,88,89,93,88,...,72,104,102,39,63,62,59,80,78,Beagle
21,42,76,106,44,78,108,46,80,110,48,...,48,120,101,35,111,85,32,114,79,Beagle
22,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Beagle

In [28]:
150 * 150

22500

In [29]:
22500 * 3

67500

## 2. Boxer

In [19]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Boxer")

In [20]:
os.listdir()

['Boxer_1.jpg',
 'Boxer_10.jpg',
 'Boxer_100.jpg',
 'Boxer_11.jpg',
 'Boxer_12.jpg',
 'Boxer_13.jpg',
 'Boxer_14.jpg',
 'Boxer_15.jpg',
 'Boxer_16.jpg',
 'Boxer_17.jpg',
 'Boxer_18.jpg',
 'Boxer_19.jpg',
 'Boxer_2.jpg',
 'Boxer_20.jpg',
 'Boxer_21.jpg',
 'Boxer_22.jpg',
 'Boxer_23.jpg',
 'Boxer_24.jpg',
 'Boxer_25.jpg',
 'Boxer_26.jpg',
 'Boxer_27.jpg',
 'Boxer_28.jpg',
 'Boxer_29.jpg',
 'Boxer_3.jpg',
 'Boxer_30.jpg',
 'Boxer_31.jpg',
 'Boxer_32.jpg',
 'Boxer_33.jpg',
 'Boxer_34.jpg',
 'Boxer_35.jpg',
 'Boxer_36.jpg',
 'Boxer_37.jpg',
 'Boxer_38.jpg',
 'Boxer_39.jpg',
 'Boxer_4.jpg',
 'Boxer_40.jpg',
 'Boxer_41.jpg',
 'Boxer_42.jpg',
 'Boxer_43.jpg',
 'Boxer_44.jpg',
 'Boxer_45.jpg',
 'Boxer_46.jpg',
 'Boxer_47.jpg',
 'Boxer_48.jpg',
 'Boxer_49.jpg',
 'Boxer_5.jpg',
 'Boxer_50.jpg',
 'Boxer_51.jpg',
 'Boxer_52.jpg',
 'Boxer_53.jpg',
 'Boxer_54.jpg',
 'Boxer_55.jpg',
 'Boxer_56.jpg',
 'Boxer_57.jpg',
 'Boxer_58.jpg',
 'Boxer_59.jpg',
 'Boxer_6.jpg',
 'Boxer_60.jpg',
 'Boxer_61.jpg',
 'Boxer_62.jpg',
 'Boxer_63.jpg',
 'Boxer_64.jpg',
 'Boxer_65.jpg',
 'Boxer_66.jpg',
 'Boxer_67.jpg',
 'Boxer_68.jpg',
 'Boxer_69.jpg',
 'Boxer_7.jpg',
 'Boxer_70.jpg',
 'Boxer_71.jpg',
 'Boxer_72.jpg',
 'Boxer_73.jpg',
 'Boxer_74.jpg',
 'Boxer_75.jpg',
 'Boxer_76.jpg',
 'Boxer_77.jpg',
 'Boxer_78.jpg',
 'Boxer_79.jpg',
 'Boxer_8.jpg',
 'Boxer_80.jpg',
 'Boxer_81.jpg',
 'Boxer_82.jpg',
 'Boxer_83.jpg',
 'Boxer_84.jpg',
 'Boxer_85.jpg',
 'Boxer_86.jpg',
 'Boxer_87.jpg',
 'Boxer_88.jpg',
 'Boxer_89.jpg',
 'Boxer_9.jpg',
 'Boxer_90.jpg',
 'Boxer_91.jpg',
 'Boxer_92.jpg',
 'Boxer_93.jpg',
 'Boxer_94.jpg',
 'Boxer_95.jpg',
 'Boxer_96.jpg',
 'Boxer_97.jpg',
 'Boxer_98.jpg',
 'Boxer_99.jpg']

In [21]:
len(os.listdir())

100

In [22]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Boxer\Boxer_14.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [23]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)
# Displaying all the images    
#     cv2.imshow('img',arr)
#     cv2.waitKey(5000)
#     cv2.destroyAllWindows()

### Creating the DataFrame

In [24]:
boxer = pd.DataFrame(images)
boxer['Breed'] = 'Boxer'

In [25]:
boxer.duplicated().sum()

79

In [26]:
len(boxer)

100

In [27]:
boxer = boxer.drop_duplicates()

In [28]:
len(boxer)

21

In [29]:
boxer.duplicated().sum()

0

In [30]:
boxer

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,89,171,149,90,172,150,91,172,151,88,...,66,139,115,56,133,118,84,161,152,Boxer
1,176,182,187,179,185,190,148,154,161,106,...,59,100,69,63,100,77,68,102,85,Boxer
2,8,15,18,5,13,16,2,11,14,4,...,125,108,112,120,105,107,119,105,107,Boxer
3,0,60,35,12,70,47,0,42,25,3,...,101,175,151,106,181,160,107,182,161,Boxer
4,9,30,27,6,26,23,5,22,18,2,...,52,135,136,45,126,129,44,125,128,Boxer
5,120,134,123,107,120,112,115,126,123,118,...,146,164,162,149,169,167,149,170,168,Boxer
6,124,130,137,103,109,116,122,129,136,102,...,129,120,120,131,122,120,132,123,120,Boxer
7,29,72,45,27,72,45,25,73,45,26,...,225,241,248,226,240,250,227,239,251,Boxer
9,21,46,32,25,50,36,29,54,40,30,...,70,163,149,96,177,164,101,178,164,Boxer
10,29,52,44,29,52,44,29,52,44,29,...,48,101,94,36,85,79,42,89,83,Boxer
11,37,51,38,38,52,40,103,118,104,35,...,142,181,138,125,166,121,126,169,124,Boxer
12,15,58,7,18,61,10,28,73,25,38,...,61,160,85,55,156,79,51,154,73,Boxer
13,213,206,197,213,206,197,213,206,197,213,...,184,172,170,189,174,172,190,175,172,Boxer
14,206,155,122,145,97,63,189,143,109,225,...,80,89,9,80,89,9,80,89,9,Boxer
17,27,30,45,27,30,45,28,31,46,29,...,104,107,115,106,108,116,106,108,116,Boxer
18,210,214,232,210,214,232,210,214,232,210,...,202,208,237,202,208,237,202,208,237,Boxer
19,107,124,137,100,117,130,93,108,124,88,...,162,168,179,158,165,180,157,164,179,Boxer
20,253,255,255,253,255,255,253,255,255,253,...,39,158,94,57,181,120,50,179,118,Boxer
21,148,177,161,148,177,161,156,185,170,161,...,43,163,152,45,166,151,53,173,157,Boxer
22,123,137,131,123,137,131,124,135,132,124,...,115,120,128,119,122,130,120,123,128,Boxer
24,242,255,252,239,253,251,236,250,250,230,...,191,228,249,198,237,252,202,242,254,Boxer

## 3. Bulldog

In [31]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Bulldog")

In [32]:
os.listdir()

['Bulldog_1.jpg',
 'Bulldog_10.jpg',
 'Bulldog_100.jpg',
 'Bulldog_11.jpg',
 'Bulldog_12.jpg',
 'Bulldog_13.jpg',
 'Bulldog_14.jpg',
 'Bulldog_15.jpg',
 'Bulldog_16.jpg',
 'Bulldog_17.jpg',
 'Bulldog_18.jpg',
 'Bulldog_19.jpg',
 'Bulldog_2.jpg',
 'Bulldog_20.jpg',
 'Bulldog_21.jpg',
 'Bulldog_22.jpg',
 'Bulldog_23.jpg',
 'Bulldog_24.jpg',
 'Bulldog_25.jpg',
 'Bulldog_26.jpg',
 'Bulldog_27.jpg',
 'Bulldog_28.jpg',
 'Bulldog_29.jpg',
 'Bulldog_3.jpg',
 'Bulldog_30.jpg',
 'Bulldog_31.jpg',
 'Bulldog_32.jpg',
 'Bulldog_33.jpg',
 'Bulldog_34.jpg',
 'Bulldog_35.jpg',
 'Bulldog_36.jpg',
 'Bulldog_37.jpg',
 'Bulldog_38.jpg',
 'Bulldog_39.jpg',
 'Bulldog_4.jpg',
 'Bulldog_40.jpg',
 'Bulldog_41.jpg',
 'Bulldog_42.jpg',
 'Bulldog_43.jpg',
 'Bulldog_44.jpg',
 'Bulldog_45.jpg',
 'Bulldog_46.jpg',
 'Bulldog_47.jpg',
 'Bulldog_48.jpg',
 'Bulldog_49.jpg',
 'Bulldog_5.jpg',
 'Bulldog_50.jpg',
 'Bulldog_51.jpg',
 'Bulldog_52.jpg',
 'Bulldog_53.jpg',
 'Bulldog_54.jpg',
 'Bulldog_55.jpg',
 'Bulldog_56.jpg',
 'Bulldog_57.jpg',
 'Bulldog_58.jpg',
 'Bulldog_59.jpg',
 'Bulldog_6.jpg',
 'Bulldog_60.jpg',
 'Bulldog_61.jpg',
 'Bulldog_62.jpg',
 'Bulldog_63.jpg',
 'Bulldog_64.jpg',
 'Bulldog_65.jpg',
 'Bulldog_66.jpg',
 'Bulldog_67.jpg',
 'Bulldog_68.jpg',
 'Bulldog_69.jpg',
 'Bulldog_7.jpg',
 'Bulldog_70.jpg',
 'Bulldog_71.jpg',
 'Bulldog_72.jpg',
 'Bulldog_73.jpg',
 'Bulldog_74.jpg',
 'Bulldog_75.jpg',
 'Bulldog_76.jpg',
 'Bulldog_77.jpg',
 'Bulldog_78.jpg',
 'Bulldog_79.jpg',
 'Bulldog_8.jpg',
 'Bulldog_80.jpg',
 'Bulldog_81.jpg',
 'Bulldog_82.jpg',
 'Bulldog_83.jpg',
 'Bulldog_84.jpg',
 'Bulldog_85.jpg',
 'Bulldog_86.jpg',
 'Bulldog_87.jpg',
 'Bulldog_88.jpg',
 'Bulldog_89.jpg',
 'Bulldog_9.jpg',
 'Bulldog_90.jpg',
 'Bulldog_91.jpg',
 'Bulldog_92.jpg',
 'Bulldog_93.jpg',
 'Bulldog_94.jpg',
 'Bulldog_95.jpg',
 'Bulldog_96.jpg',
 'Bulldog_97.jpg',
 'Bulldog_98.jpg',
 'Bulldog_99.jpg']

In [33]:
len(os.listdir())

100

In [34]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Bulldog\Bulldog_86.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [35]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

### Creating the DataFrame

In [36]:
bulldog = pd.DataFrame(images)
bulldog['Breed'] = 'Bulldog'

In [37]:
len(bulldog)

100

In [38]:
bulldog.duplicated().sum()

77

In [39]:
bulldog = bulldog.drop_duplicates()

In [40]:
len(bulldog)

23

In [41]:
bulldog.duplicated().sum()

0

In [42]:
bulldog

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,30,33,61,27,30,58,23,26,54,19,...,45,96,73,28,83,56,27,85,56,Bulldog
1,54,159,122,54,159,122,55,160,123,57,...,49,111,91,55,115,92,58,116,91,Bulldog
2,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Bulldog
3,100,125,132,66,92,98,46,70,77,45,...,79,96,115,77,93,116,75,92,118,Bulldog
4,201,217,246,201,217,246,201,217,246,202,...,240,246,253,241,247,254,241,247,254,Bulldog
5,30,97,70,33,101,73,33,100,73,28,...,7,76,52,12,83,57,30,101,75,Bulldog
6,59,88,85,15,46,43,17,52,46,3,...,67,156,88,49,136,68,47,133,63,Bulldog
7,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Bulldog
9,0,43,111,0,43,110,0,41,107,0,...,22,110,122,17,98,106,5,83,86,Bulldog
10,16,23,18,16,23,18,16,23,18,16,...,46,51,60,47,50,59,47,50,58,Bulldog
11,124,202,179,128,205,183,135,210,188,139,...,92,174,142,87,173,139,88,175,141,Bulldog
12,37,91,78,38,92,79,38,92,79,39,...,84,152,135,84,149,133,84,149,133,Bulldog
13,10,11,37,8,12,37,0,2,27,30,...,29,35,78,30,34,75,30,35,74,Bulldog
14,29,20,30,28,19,30,34,26,36,42,...,52,60,73,49,56,67,49,56,65,Bulldog
17,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Bulldog
18,23,22,26,23,22,26,25,22,24,26,...,45,103,65,49,103,69,52,102,70,Bulldog
19,219,204,201,221,206,203,223,208,205,222,...,6,81,83,1,76,79,1,75,79,Bulldog
20,26,74,53,44,89,71,44,83,73,26,...,44,134,99,52,142,112,54,144,115,Bulldog
21,37,97,66,35,95,65,36,95,67,27,...,74,86,110,76,91,114,74,93,114,Bulldog
22,48,50,61,47,49,60,52,54,65,59,...,173,167,154,170,164,151,170,164,151,Bulldog
24,58,153,133,58,153,133,57,151,134,57,...,26,66,62,43,79,74,54,88,82,Bulldog
59,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Bulldog
80,42,84,129,50,92,134,54,88,127,100,...,92,123,146,89,118,142,85,111,135,Bulldog

## 4. Dachshund

In [43]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Dachshund")

In [44]:
os.listdir()

['Dachshund_1.jpg',
 'Dachshund_10.jpg',
 'Dachshund_100.jpg',
 'Dachshund_11.jpg',
 'Dachshund_12.jpg',
 'Dachshund_13.jpg',
 'Dachshund_14.jpg',
 'Dachshund_16.jpg',
 'Dachshund_17.jpg',
 'Dachshund_18.jpg',
 'Dachshund_19.jpg',
 'Dachshund_2.jpg',
 'Dachshund_20.jpg',
 'Dachshund_21.jpg',
 'Dachshund_22.jpg',
 'Dachshund_23.jpg',
 'Dachshund_24.jpg',
 'Dachshund_25.jpg',
 'Dachshund_26.jpg',
 'Dachshund_27.jpg',
 'Dachshund_28.jpg',
 'Dachshund_29.jpg',
 'Dachshund_3.jpg',
 'Dachshund_30.jpg',
 'Dachshund_31.jpg',
 'Dachshund_32.jpg',
 'Dachshund_33.jpg',
 'Dachshund_34.jpg',
 'Dachshund_35.jpg',
 'Dachshund_36.jpg',
 'Dachshund_37.jpg',
 'Dachshund_38.jpg',
 'Dachshund_39.jpg',
 'Dachshund_4.jpg',
 'Dachshund_40.jpg',
 'Dachshund_41.jpg',
 'Dachshund_42.jpg',
 'Dachshund_43.jpg',
 'Dachshund_44.jpg',
 'Dachshund_45.jpg',
 'Dachshund_46.jpg',
 'Dachshund_47.jpg',
 'Dachshund_48.jpg',
 'Dachshund_49.jpg',
 'Dachshund_5.jpg',
 'Dachshund_50.jpg',
 'Dachshund_51.jpg',
 'Dachshund_52.jpg',
 'Dachshund_53.jpg',
 'Dachshund_54.jpg',
 'Dachshund_55.jpg',
 'Dachshund_56.jpg',
 'Dachshund_58.jpg',
 'Dachshund_59.jpg',
 'Dachshund_6.jpg',
 'Dachshund_60.jpg',
 'Dachshund_61.jpg',
 'Dachshund_62.jpg',
 'Dachshund_63.jpg',
 'Dachshund_64.jpg',
 'Dachshund_65.jpg',
 'Dachshund_66.jpg',
 'Dachshund_67.jpg',
 'Dachshund_68.jpg',
 'Dachshund_69.jpg',
 'Dachshund_7.jpg',
 'Dachshund_70.jpg',
 'Dachshund_71.jpg',
 'Dachshund_72.jpg',
 'Dachshund_73.jpg',
 'Dachshund_74.jpg',
 'Dachshund_75.jpg',
 'Dachshund_76.jpg',
 'Dachshund_77.jpg',
 'Dachshund_79.jpg',
 'Dachshund_8.jpg',
 'Dachshund_80.jpg',
 'Dachshund_81.jpg',
 'Dachshund_82.jpg',
 'Dachshund_83.jpg',
 'Dachshund_84.jpg',
 'Dachshund_85.jpg',
 'Dachshund_86.jpg',
 'Dachshund_87.jpg',
 'Dachshund_88.jpg',
 'Dachshund_89.jpg',
 'Dachshund_9.jpg',
 'Dachshund_90.jpg',
 'Dachshund_91.jpg',
 'Dachshund_92.jpg',
 'Dachshund_93.jpg',
 'Dachshund_94.jpg',
 'Dachshund_95.jpg',
 'Dachshund_96.jpg',
 'Dachshund_97.jpg',
 'Dachshund_98.jpg']

In [45]:
len(os.listdir())

96

In [46]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Dachshund\Dachshund_14.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [47]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

### Creating the DataFrame

In [48]:
dachshund = pd.DataFrame(images)
dachshund['Breed'] = "Dachshund"

In [49]:
len(dachshund)

96

In [50]:
dachshund.duplicated().sum()

75

In [51]:
dachshund = dachshund.drop_duplicates()

In [52]:
len(dachshund)

21

In [53]:
dachshund.duplicated().sum()

0

In [54]:
dachshund

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,15,37,42,18,43,47,18,43,49,11,...,103,101,100,100,98,97,100,98,97,Dachshund
1,40,53,55,53,66,68,64,77,79,62,...,182,193,197,168,178,181,170,179,182,Dachshund
2,79,118,156,88,127,165,101,140,179,114,...,96,111,143,104,119,151,105,121,150,Dachshund
3,38,58,45,40,60,47,40,63,49,39,...,64,54,37,59,48,33,58,47,33,Dachshund
4,36,89,79,39,92,82,42,96,86,45,...,94,153,125,85,146,120,85,146,120,Dachshund
5,191,186,183,186,181,179,184,179,176,188,...,179,203,233,181,206,236,182,206,236,Dachshund
6,122,202,167,113,193,158,130,212,177,164,...,87,162,130,89,164,134,96,170,140,Dachshund
8,246,255,255,249,255,255,255,254,255,255,...,254,254,254,255,255,255,255,255,255,Dachshund
9,72,91,94,72,91,94,73,92,95,74,...,56,53,45,50,48,40,50,47,39,Dachshund
10,114,168,155,96,150,137,111,165,152,113,...,102,146,140,126,170,164,103,144,139,Dachshund
11,206,199,190,205,198,189,205,198,189,206,...,83,99,122,103,120,147,70,87,114,Dachshund
12,255,249,247,255,251,247,255,249,245,255,...,135,165,193,138,169,201,123,154,188,Dachshund
13,150,157,160,150,157,160,150,157,160,150,...,57,55,51,109,108,104,198,197,193,Dachshund
16,56,57,55,58,59,57,60,61,59,62,...,26,30,25,28,32,27,28,32,27,Dachshund
17,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Dachshund
18,149,195,206,149,195,206,150,196,207,150,...,163,182,185,167,186,189,169,188,191,Dachshund
19,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Dachshund
20,142,127,148,143,123,142,141,117,131,143,...,242,245,249,239,242,246,239,242,246,Dachshund
21,16,119,58,9,111,51,9,109,49,23,...,62,157,100,79,155,97,90,156,97,Dachshund
23,72,174,139,92,194,159,88,192,157,73,...,130,139,138,131,135,140,123,125,133,Dachshund
29,189,207,236,186,206,237,187,206,240,189,...,185,207,242,185,207,242,185,207,242,Dachshund

## 5. German Shephard

In [55]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\German_Shepherd")

In [56]:
os.listdir()

['German Shepherd_1.jpg',
 'German Shepherd_10.jpg',
 'German Shepherd_100.jpg',
 'German Shepherd_11.jpg',
 'German Shepherd_12.jpg',
 'German Shepherd_13.jpg',
 'German Shepherd_14.jpg',
 'German Shepherd_15.jpg',
 'German Shepherd_16.jpg',
 'German Shepherd_17.jpg',
 'German Shepherd_18.jpg',
 'German Shepherd_19.jpg',
 'German Shepherd_2.jpg',
 'German Shepherd_20.jpg',
 'German Shepherd_21.jpg',
 'German Shepherd_22.jpg',
 'German Shepherd_23.jpg',
 'German Shepherd_24.jpg',
 'German Shepherd_25.jpg',
 'German Shepherd_26.jpg',
 'German Shepherd_27.jpg',
 'German Shepherd_28.jpg',
 'German Shepherd_29.jpg',
 'German Shepherd_3.jpg',
 'German Shepherd_31.jpg',
 'German Shepherd_32.jpg',
 'German Shepherd_33.jpg',
 'German Shepherd_34.jpg',
 'German Shepherd_35.jpg',
 'German Shepherd_36.jpg',
 'German Shepherd_37.jpg',
 'German Shepherd_38.jpg',
 'German Shepherd_39.jpg',
 'German Shepherd_4.jpg',
 'German Shepherd_40.jpg',
 'German Shepherd_41.jpg',
 'German Shepherd_42.jpg',
 'German Shepherd_43.jpg',
 'German Shepherd_44.jpg',
 'German Shepherd_45.jpg',
 'German Shepherd_46.jpg',
 'German Shepherd_47.jpg',
 'German Shepherd_48.jpg',
 'German Shepherd_49.jpg',
 'German Shepherd_5.jpg',
 'German Shepherd_50.jpg',
 'German Shepherd_51.jpg',
 'German Shepherd_52.jpg',
 'German Shepherd_53.jpg',
 'German Shepherd_54.jpg',
 'German Shepherd_55.jpg',
 'German Shepherd_56.jpg',
 'German Shepherd_57.jpg',
 'German Shepherd_58.jpg',
 'German Shepherd_59.jpg',
 'German Shepherd_6.jpg',
 'German Shepherd_60.jpg',
 'German Shepherd_61.jpg',
 'German Shepherd_62.jpg',
 'German Shepherd_63.jpg',
 'German Shepherd_64.jpg',
 'German Shepherd_65.jpg',
 'German Shepherd_66.jpg',
 'German Shepherd_67.jpg',
 'German Shepherd_68.jpg',
 'German Shepherd_69.jpg',
 'German Shepherd_7.jpg',
 'German Shepherd_70.jpg',
 'German Shepherd_71.jpg',
 'German Shepherd_73.jpg',
 'German Shepherd_74.jpg',
 'German Shepherd_75.jpg',
 'German Shepherd_76.jpg',
 'German Shepherd_77.jpg',
 'German Shepherd_78.jpg',
 'German Shepherd_79.jpg',
 'German Shepherd_8.jpg',
 'German Shepherd_80.jpg',
 'German Shepherd_81.jpg',
 'German Shepherd_82.jpg',
 'German Shepherd_83.jpg',
 'German Shepherd_84.jpg',
 'German Shepherd_85.jpg',
 'German Shepherd_86.jpg',
 'German Shepherd_87.jpg',
 'German Shepherd_88.jpg',
 'German Shepherd_89.jpg',
 'German Shepherd_90.jpg',
 'German Shepherd_91.jpg',
 'German Shepherd_93.jpg',
 'German Shepherd_94.jpg',
 'German Shepherd_95.jpg',
 'German Shepherd_96.jpg',
 'German Shepherd_97.jpg',
 'German Shepherd_98.jpg',
 'German Shepherd_99.jpg']

In [57]:
len(os.listdir())

96

In [58]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\German_Shepherd\German Shepherd_17.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [59]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

In [60]:
german = pd.DataFrame(images)

In [61]:
german['Breed'] = 'German Shephard'

In [62]:
len(german)

96

In [63]:
german.duplicated().sum()

75

In [63]:
german = german.drop_duplicates()

In [64]:
len(german)

21

In [65]:
german.duplicated().sum()

0

In [66]:
german

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,185,172,110,178,165,103,183,170,108,188,...,182,198,205,186,200,206,189,201,207,German Shephard
1,181,183,183,177,178,178,178,179,179,182,...,103,104,102,108,109,107,109,110,108,German Shephard
2,70,176,163,70,176,163,71,177,164,72,...,65,165,155,52,167,145,52,177,149,German Shephard
3,0,0,6,0,0,6,0,0,6,0,...,0,0,0,0,0,0,0,0,0,German Shephard
4,20,76,95,0,53,72,2,52,71,11,...,25,64,104,45,84,122,46,85,123,German Shephard
5,160,229,114,179,246,130,173,235,119,175,...,54,84,113,65,98,130,61,93,128,German Shephard
6,250,253,255,250,253,255,250,254,255,250,...,255,255,255,255,255,255,255,255,255,German Shephard
7,240,230,223,216,206,199,200,190,183,175,...,113,122,135,125,135,145,134,144,154,German Shephard
9,110,106,87,110,106,87,110,106,87,111,...,139,166,183,163,178,186,164,175,173,German Shephard
10,229,213,177,230,214,178,230,214,178,230,...,140,168,183,127,156,171,127,158,173,German Shephard
11,10,15,13,9,14,12,7,12,10,6,...,175,205,230,178,208,233,180,210,235,German Shephard
12,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,German Shephard
13,255,197,137,255,198,136,253,199,134,244,...,38,78,53,30,74,49,29,76,50,German Shephard
14,85,95,59,71,80,50,62,71,50,62,...,141,173,196,145,177,200,145,177,200,German Shephard
17,255,255,255,255,255,255,255,255,255,255,...,255,252,255,255,254,255,255,255,255,German Shephard
18,155,165,189,156,166,190,162,170,193,170,...,74,194,146,69,195,146,67,195,146,German Shephard
19,93,154,164,93,154,164,93,155,163,93,...,88,152,147,83,149,144,83,149,144,German Shephard
20,119,162,151,50,96,84,63,110,98,70,...,89,109,140,86,103,132,88,102,130,German Shephard
21,9,25,32,10,29,35,16,36,43,21,...,77,209,223,78,206,225,80,205,225,German Shephard
22,24,54,41,22,52,39,23,51,38,24,...,90,159,138,103,168,146,109,171,149,German Shephard
46,242,244,244,242,244,244,242,244,244,242,...,255,255,255,255,255,255,255,255,255,German Shephard

## 6. Golden Retriever

In [67]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Golden_Retriever")

In [68]:
os.listdir()

['Golden Retriever_1.jpg',
 'Golden Retriever_10.jpg',
 'Golden Retriever_100.jpg',
 'Golden Retriever_12.jpg',
 'Golden Retriever_13.jpg',
 'Golden Retriever_14.jpg',
 'Golden Retriever_15.jpg',
 'Golden Retriever_16.jpg',
 'Golden Retriever_18.jpg',
 'Golden Retriever_19.jpg',
 'Golden Retriever_2.jpg',
 'Golden Retriever_20.jpg',
 'Golden Retriever_21.jpg',
 'Golden Retriever_22.jpg',
 'Golden Retriever_23.jpg',
 'Golden Retriever_24.jpg',
 'Golden Retriever_25.jpg',
 'Golden Retriever_26.jpg',
 'Golden Retriever_27.jpg',
 'Golden Retriever_28.jpg',
 'Golden Retriever_29.jpg',
 'Golden Retriever_3.jpg',
 'Golden Retriever_30.jpg',
 'Golden Retriever_31.jpg',
 'Golden Retriever_33.jpg',
 'Golden Retriever_34.jpg',
 'Golden Retriever_35.jpg',
 'Golden Retriever_36.jpg',
 'Golden Retriever_37.jpg',
 'Golden Retriever_39.jpg',
 'Golden Retriever_4.jpg',
 'Golden Retriever_40.jpg',
 'Golden Retriever_41.jpg',
 'Golden Retriever_42.jpg',
 'Golden Retriever_43.jpg',
 'Golden Retriever_44.jpg',
 'Golden Retriever_45.jpg',
 'Golden Retriever_46.jpg',
 'Golden Retriever_47.jpg',
 'Golden Retriever_48.jpg',
 'Golden Retriever_49.jpg',
 'Golden Retriever_5.jpg',
 'Golden Retriever_50.jpg',
 'Golden Retriever_51.jpg',
 'Golden Retriever_52.jpg',
 'Golden Retriever_54.jpg',
 'Golden Retriever_55.jpg',
 'Golden Retriever_56.jpg',
 'Golden Retriever_57.jpg',
 'Golden Retriever_58.jpg',
 'Golden Retriever_6.jpg',
 'Golden Retriever_60.jpg',
 'Golden Retriever_61.jpg',
 'Golden Retriever_62.jpg',
 'Golden Retriever_63.jpg',
 'Golden Retriever_64.jpg',
 'Golden Retriever_65.jpg',
 'Golden Retriever_66.jpg',
 'Golden Retriever_67.jpg',
 'Golden Retriever_68.jpg',
 'Golden Retriever_69.jpg',
 'Golden Retriever_7.jpg',
 'Golden Retriever_70.jpg',
 'Golden Retriever_71.jpg',
 'Golden Retriever_72.jpg',
 'Golden Retriever_73.jpg',
 'Golden Retriever_75.jpg',
 'Golden Retriever_76.jpg',
 'Golden Retriever_77.jpg',
 'Golden Retriever_78.jpg',
 'Golden Retriever_79.jpg',
 'Golden Retriever_8.jpg',
 'Golden Retriever_81.jpg',
 'Golden Retriever_82.jpg',
 'Golden Retriever_83.jpg',
 'Golden Retriever_84.jpg',
 'Golden Retriever_85.jpg',
 'Golden Retriever_86.jpg',
 'Golden Retriever_87.jpg',
 'Golden Retriever_88.jpg',
 'Golden Retriever_89.jpg',
 'Golden Retriever_9.jpg',
 'Golden Retriever_90.jpg',
 'Golden Retriever_91.jpg',
 'Golden Retriever_92.jpg',
 'Golden Retriever_93.jpg',
 'Golden Retriever_94.jpg',
 'Golden Retriever_96.jpg',
 'Golden Retriever_97.jpg',
 'Golden Retriever_98.jpg',
 'Golden Retriever_99.jpg']

In [69]:
len(os.listdir())

91

In [70]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Golden_Retriever\Golden Retriever_37.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [71]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

### Creating the DataFrame

In [72]:
retriever = pd.DataFrame(images)

In [73]:
retriever['Breed'] = 'Golden Retriever'

In [74]:
len(retriever)

91

In [75]:
retriever.duplicated().sum()

72

In [76]:
retriever = retriever.drop_duplicates()

In [77]:
len(retriever)

19

In [78]:
retriever.duplicated().sum()

0

In [79]:
retriever

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,0,10,18,0,10,18,1,12,20,7,...,86,95,92,98,107,104,107,116,113,Golden Retriever
1,37,93,74,37,93,74,37,92,73,37,...,161,190,221,144,176,215,137,170,215,Golden Retriever
2,81,86,85,81,86,85,81,86,85,81,...,43,166,127,47,170,130,56,181,141,Golden Retriever
3,167,176,186,167,176,186,167,176,186,167,...,181,186,188,175,181,186,175,181,186,Golden Retriever
4,22,37,40,31,45,47,31,43,45,35,...,114,124,142,151,161,179,146,156,174,Golden Retriever
5,255,253,246,255,253,246,255,253,244,255,...,21,121,65,29,130,74,42,143,87,Golden Retriever
6,222,231,234,222,231,234,223,232,235,224,...,76,86,74,80,87,75,87,93,82,Golden Retriever
8,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Golden Retriever
9,79,163,161,81,166,162,80,165,160,73,...,85,149,153,32,97,105,117,183,194,Golden Retriever
10,109,117,124,114,122,129,116,124,131,117,...,191,214,229,189,213,225,189,213,225,Golden Retriever
11,117,110,101,118,111,102,118,111,102,119,...,11,51,46,5,42,38,6,43,39,Golden Retriever
12,246,247,245,245,246,244,242,243,241,240,...,136,145,172,91,100,127,47,56,83,Golden Retriever
15,238,210,193,238,210,193,238,210,193,238,...,87,174,200,86,173,199,85,172,198,Golden Retriever
16,89,129,157,103,143,172,126,169,198,160,...,81,151,184,61,109,142,52,87,117,Golden Retriever
17,12,25,23,12,25,23,13,27,25,16,...,94,131,145,95,132,146,99,136,150,Golden Retriever
18,13,13,13,13,13,13,13,13,13,12,...,125,184,158,124,185,159,149,210,184,Golden Retriever
19,54,65,79,63,74,88,56,67,81,53,...,77,103,122,96,116,142,101,117,146,Golden Retriever
20,62,153,168,67,158,173,77,164,180,84,...,106,211,224,108,214,227,110,214,227,Golden Retriever
22,43,82,60,37,76,54,30,69,47,27,...,46,74,71,13,44,47,9,44,48,Golden Retriever

## 7. Labrador

In [88]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Labrador_Retriever")

In [89]:
os.listdir()

['Labrador Retriever_1.jpg',
 'Labrador Retriever_10.jpg',
 'Labrador Retriever_100.jpg',
 'Labrador Retriever_11.jpg',
 'Labrador Retriever_12.jpg',
 'Labrador Retriever_13.jpg',
 'Labrador Retriever_14.jpg',
 'Labrador Retriever_15.jpg',
 'Labrador Retriever_16.jpg',
 'Labrador Retriever_17.jpg',
 'Labrador Retriever_18.jpg',
 'Labrador Retriever_19.jpg',
 'Labrador Retriever_2.jpg',
 'Labrador Retriever_20.jpg',
 'Labrador Retriever_21.jpg',
 'Labrador Retriever_22.jpg',
 'Labrador Retriever_23.jpg',
 'Labrador Retriever_24.jpg',
 'Labrador Retriever_25.jpg',
 'Labrador Retriever_26.jpg',
 'Labrador Retriever_27.jpg',
 'Labrador Retriever_28.jpg',
 'Labrador Retriever_3.jpg',
 'Labrador Retriever_30.jpg',
 'Labrador Retriever_31.jpg',
 'Labrador Retriever_32.jpg',
 'Labrador Retriever_33.jpg',
 'Labrador Retriever_34.jpg',
 'Labrador Retriever_35.jpg',
 'Labrador Retriever_36.jpg',
 'Labrador Retriever_37.jpg',
 'Labrador Retriever_38.jpg',
 'Labrador Retriever_39.jpg',
 'Labrador Retriever_4.jpg',
 'Labrador Retriever_40.jpg',
 'Labrador Retriever_41.jpg',
 'Labrador Retriever_42.jpg',
 'Labrador Retriever_43.jpg',
 'Labrador Retriever_44.jpg',
 'Labrador Retriever_45.jpg',
 'Labrador Retriever_46.jpg',
 'Labrador Retriever_47.jpg',
 'Labrador Retriever_48.jpg',
 'Labrador Retriever_49.jpg',
 'Labrador Retriever_5.jpg',
 'Labrador Retriever_51.jpg',
 'Labrador Retriever_52.jpg',
 'Labrador Retriever_53.jpg',
 'Labrador Retriever_54.jpg',
 'Labrador Retriever_55.jpg',
 'Labrador Retriever_56.jpg',
 'Labrador Retriever_57.jpg',
 'Labrador Retriever_58.jpg',
 'Labrador Retriever_59.jpg',
 'Labrador Retriever_6.jpg',
 'Labrador Retriever_60.jpg',
 'Labrador Retriever_61.jpg',
 'Labrador Retriever_62.jpg',
 'Labrador Retriever_63.jpg',
 'Labrador Retriever_64.jpg',
 'Labrador Retriever_65.jpg',
 'Labrador Retriever_66.jpg',
 'Labrador Retriever_67.jpg',
 'Labrador Retriever_68.jpg',
 'Labrador Retriever_69.jpg',
 'Labrador Retriever_7.jpg',
 'Labrador Retriever_70.jpg',
 'Labrador Retriever_72.jpg',
 'Labrador Retriever_73.jpg',
 'Labrador Retriever_74.jpg',
 'Labrador Retriever_75.jpg',
 'Labrador Retriever_76.jpg',
 'Labrador Retriever_77.jpg',
 'Labrador Retriever_78.jpg',
 'Labrador Retriever_79.jpg',
 'Labrador Retriever_80.jpg',
 'Labrador Retriever_81.jpg',
 'Labrador Retriever_82.jpg',
 'Labrador Retriever_83.jpg',
 'Labrador Retriever_84.jpg',
 'Labrador Retriever_85.jpg',
 'Labrador Retriever_86.jpg',
 'Labrador Retriever_87.jpg',
 'Labrador Retriever_88.jpg',
 'Labrador Retriever_89.jpg',
 'Labrador Retriever_9.jpg',
 'Labrador Retriever_90.jpg',
 'Labrador Retriever_91.jpg',
 'Labrador Retriever_93.jpg',
 'Labrador Retriever_94.jpg',
 'Labrador Retriever_95.jpg',
 'Labrador Retriever_96.jpg',
 'Labrador Retriever_97.jpg',
 'Labrador Retriever_98.jpg',
 'Labrador Retriever_99.jpg']

In [90]:
len(os.listdir())

95

In [91]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Labrador_Retriever\Labrador Retriever_66.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [92]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

In [93]:
lab = pd.DataFrame(images)

In [94]:
lab['Breed'] = 'Labrador Retriever'

In [95]:
len(lab)

95

In [96]:
lab.duplicated().sum()

73

In [97]:
lab = lab.drop_duplicates()

In [98]:
len(lab)

22

In [99]:
lab.duplicated().sum()

0

In [100]:
lab

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,86,119,121,29,62,65,45,75,76,60,...,69,103,107,82,125,132,60,107,115,Labrador Retriever
1,30,65,55,26,61,51,22,56,46,17,...,24,59,59,16,52,52,4,42,42,Labrador Retriever
2,53,80,77,45,72,69,39,63,61,39,...,91,141,141,78,127,125,67,117,113,Labrador Retriever
3,56,86,81,79,109,104,83,113,108,79,...,100,129,143,122,149,164,108,134,150,Labrador Retriever
4,69,133,111,69,133,111,69,133,111,68,...,67,133,108,67,133,108,67,133,108,Labrador Retriever
5,77,111,100,54,86,75,47,74,64,53,...,206,214,209,218,217,216,214,209,210,Labrador Retriever
6,102,230,201,102,230,201,105,232,202,108,...,34,117,79,19,102,64,26,109,71,Labrador Retriever
8,116,119,133,60,66,79,32,45,55,12,...,38,79,81,55,98,101,72,115,118,Labrador Retriever
9,255,255,255,255,255,255,255,255,255,255,...,254,254,254,255,255,255,255,255,255,Labrador Retriever
10,236,238,239,236,238,239,236,238,239,236,...,114,116,117,112,111,113,114,111,113,Labrador Retriever
11,85,192,153,88,195,156,93,200,161,97,...,77,195,144,95,210,161,100,212,165,Labrador Retriever
12,8,40,35,19,51,46,29,61,56,27,...,66,117,137,78,128,148,83,133,151,Labrador Retriever
13,255,255,255,255,255,255,255,255,255,255,...,255,255,254,255,255,254,255,255,254,Labrador Retriever
14,100,158,134,111,169,144,124,182,158,126,...,76,134,105,102,156,129,55,108,81,Labrador Retriever
17,24,92,127,18,89,123,34,106,139,72,...,105,196,236,83,184,219,69,178,210,Labrador Retriever
18,21,54,33,3,35,14,1,27,8,8,...,62,169,137,56,163,136,55,162,135,Labrador Retriever
19,79,122,85,91,134,97,104,147,110,88,...,5,38,11,20,54,26,43,76,49,Labrador Retriever
20,200,226,249,140,215,227,88,207,208,91,...,83,155,131,88,150,120,89,149,118,Labrador Retriever
21,102,186,168,109,193,175,112,193,174,110,...,123,188,176,108,180,164,110,185,169,Labrador Retriever
23,29,64,58,45,81,75,64,100,94,61,...,40,102,71,48,116,85,41,111,80,Labrador Retriever
57,104,163,149,112,171,157,119,177,163,120,...,89,147,129,104,162,148,72,130,119,Labrador Retriever
58,243,237,238,242,236,237,241,236,236,240,...,202,202,208,202,202,208,199,199,205,Labrador Retriever

## 8. Poodle

In [101]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Poodle")

In [102]:
os.listdir()

['Poodle_1.jpg',
 'Poodle_10.jpg',
 'Poodle_100.jpg',
 'Poodle_11.jpg',
 'Poodle_12.jpg',
 'Poodle_13.jpg',
 'Poodle_14.jpg',
 'Poodle_15.jpg',
 'Poodle_16.jpg',
 'Poodle_17.jpg',
 'Poodle_18.jpg',
 'Poodle_19.jpg',
 'Poodle_2.jpg',
 'Poodle_20.jpg',
 'Poodle_21.jpg',
 'Poodle_22.jpg',
 'Poodle_23.jpg',
 'Poodle_24.jpg',
 'Poodle_25.jpg',
 'Poodle_26.jpg',
 'Poodle_27.jpg',
 'Poodle_28.jpg',
 'Poodle_29.jpg',
 'Poodle_3.jpg',
 'Poodle_30.jpg',
 'Poodle_31.jpg',
 'Poodle_32.jpg',
 'Poodle_33.jpg',
 'Poodle_34.jpg',
 'Poodle_35.jpg',
 'Poodle_36.jpg',
 'Poodle_37.jpg',
 'Poodle_38.jpg',
 'Poodle_39.jpg',
 'Poodle_4.jpg',
 'Poodle_40.jpg',
 'Poodle_41.jpg',
 'Poodle_42.jpg',
 'Poodle_43.jpg',
 'Poodle_44.jpg',
 'Poodle_45.jpg',
 'Poodle_46.jpg',
 'Poodle_47.jpg',
 'Poodle_48.jpg',
 'Poodle_49.jpg',
 'Poodle_5.jpg',
 'Poodle_50.jpg',
 'Poodle_51.jpg',
 'Poodle_52.jpg',
 'Poodle_53.jpg',
 'Poodle_54.jpg',
 'Poodle_55.jpg',
 'Poodle_56.jpg',
 'Poodle_57.jpg',
 'Poodle_58.jpg',
 'Poodle_59.jpg',
 'Poodle_6.jpg',
 'Poodle_60.jpg',
 'Poodle_61.jpg',
 'Poodle_62.jpg',
 'Poodle_63.jpg',
 'Poodle_64.jpg',
 'Poodle_65.jpg',
 'Poodle_66.jpg',
 'Poodle_67.jpg',
 'Poodle_68.jpg',
 'Poodle_69.jpg',
 'Poodle_7.jpg',
 'Poodle_70.jpg',
 'Poodle_71.jpg',
 'Poodle_72.jpg',
 'Poodle_73.jpg',
 'Poodle_74.jpg',
 'Poodle_75.jpg',
 'Poodle_76.jpg',
 'Poodle_77.jpg',
 'Poodle_78.jpg',
 'Poodle_79.jpg',
 'Poodle_8.jpg',
 'Poodle_80.jpg',
 'Poodle_81.jpg',
 'Poodle_82.jpg',
 'Poodle_83.jpg',
 'Poodle_84.jpg',
 'Poodle_85.jpg',
 'Poodle_86.jpg',
 'Poodle_87.jpg',
 'Poodle_88.jpg',
 'Poodle_89.jpg',
 'Poodle_9.jpg',
 'Poodle_90.jpg',
 'Poodle_91.jpg',
 'Poodle_92.jpg',
 'Poodle_93.jpg',
 'Poodle_94.jpg',
 'Poodle_95.jpg',
 'Poodle_96.jpg',
 'Poodle_97.jpg',
 'Poodle_98.jpg',
 'Poodle_99.jpg']

In [103]:
len(os.listdir())

100

In [104]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Poodle\Poodle_14.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [105]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

In [106]:
poodle = pd.DataFrame(images)

In [107]:
poodle['Breed'] = 'Poodle'

In [108]:
len(poodle)

100

In [109]:
poodle.duplicated().sum()

79

In [110]:
poodle = poodle.drop_duplicates()

In [111]:
len(poodle)

21

In [112]:
poodle.duplicated().sum()

0

In [113]:
poodle

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,109,96,98,110,97,99,112,99,101,114,...,86,93,102,86,93,102,86,93,102,Poodle
1,24,38,36,15,29,27,9,23,21,22,...,50,92,81,53,90,80,55,90,80,Poodle
2,31,65,34,32,66,35,32,66,35,32,...,77,171,117,71,168,116,68,167,117,Poodle
3,120,136,183,120,136,183,120,136,183,120,...,203,213,243,203,213,243,203,213,243,Poodle
4,166,209,212,162,205,208,159,202,205,160,...,120,119,128,169,166,175,140,137,146,Poodle
5,152,145,128,155,147,130,95,84,70,49,...,173,208,222,169,206,220,160,197,211,Poodle
6,1,7,6,8,14,13,8,14,13,2,...,251,246,248,249,244,246,247,242,244,Poodle
7,72,117,100,67,113,96,66,114,96,72,...,205,205,205,205,205,205,205,205,205,Poodle
9,78,95,98,64,83,85,50,70,71,43,...,228,214,208,227,213,207,227,213,207,Poodle
10,159,161,169,159,161,169,159,161,169,159,...,213,216,221,212,215,220,212,215,220,Poodle
11,29,56,36,18,46,26,15,43,24,22,...,56,136,101,50,126,95,52,126,96,Poodle
12,176,206,223,145,175,192,101,131,148,79,...,74,141,102,92,157,120,94,158,123,Poodle
13,128,159,144,123,154,138,121,150,134,119,...,152,148,147,152,148,147,152,148,147,Poodle
14,183,132,89,190,144,100,182,142,100,175,...,20,60,55,37,77,74,44,81,79,Poodle
17,52,162,104,54,166,108,61,176,115,68,...,61,122,81,74,136,95,86,149,107,Poodle
18,38,105,83,18,76,55,64,106,88,178,...,40,139,99,45,138,99,38,129,90,Poodle
19,41,45,39,35,40,33,54,59,54,102,...,42,96,75,62,112,94,87,136,120,Poodle
20,207,220,242,208,221,243,210,223,247,212,...,166,191,213,167,191,213,166,190,212,Poodle
21,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Poodle
22,1,36,40,11,46,50,13,48,52,21,...,70,95,121,72,99,130,55,83,117,Poodle
24,100,114,143,100,114,143,100,114,143,100,...,105,120,139,101,116,139,100,115,141,Poodle

## 9. Rottweiler

In [114]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Rottweiler")

In [115]:
os.listdir()

['Rottweiler_1.jpg',
 'Rottweiler_10.jpg',
 'Rottweiler_100.jpg',
 'Rottweiler_11.jpg',
 'Rottweiler_12.jpg',
 'Rottweiler_13.jpg',
 'Rottweiler_14.jpg',
 'Rottweiler_15.jpg',
 'Rottweiler_16.jpg',
 'Rottweiler_17.jpg',
 'Rottweiler_18.jpg',
 'Rottweiler_2.jpg',
 'Rottweiler_21.jpg',
 'Rottweiler_22.jpg',
 'Rottweiler_23.jpg',
 'Rottweiler_24.jpg',
 'Rottweiler_25.jpg',
 'Rottweiler_26.jpg',
 'Rottweiler_28.jpg',
 'Rottweiler_29.jpg',
 'Rottweiler_3.jpg',
 'Rottweiler_30.jpg',
 'Rottweiler_31.jpg',
 'Rottweiler_32.jpg',
 'Rottweiler_33.jpg',
 'Rottweiler_34.jpg',
 'Rottweiler_35.jpg',
 'Rottweiler_36.jpg',
 'Rottweiler_37.jpg',
 'Rottweiler_38.jpg',
 'Rottweiler_39.jpg',
 'Rottweiler_4.jpg',
 'Rottweiler_40.jpg',
 'Rottweiler_42.jpg',
 'Rottweiler_43.jpg',
 'Rottweiler_44.jpg',
 'Rottweiler_45.jpg',
 'Rottweiler_46.jpg',
 'Rottweiler_47.jpg',
 'Rottweiler_49.jpg',
 'Rottweiler_5.jpg',
 'Rottweiler_50.jpg',
 'Rottweiler_51.jpg',
 'Rottweiler_52.jpg',
 'Rottweiler_53.jpg',
 'Rottweiler_54.jpg',
 'Rottweiler_55.jpg',
 'Rottweiler_56.jpg',
 'Rottweiler_57.jpg',
 'Rottweiler_58.jpg',
 'Rottweiler_59.jpg',
 'Rottweiler_6.jpg',
 'Rottweiler_61.jpg',
 'Rottweiler_63.jpg',
 'Rottweiler_64.jpg',
 'Rottweiler_65.jpg',
 'Rottweiler_66.jpg',
 'Rottweiler_67.jpg',
 'Rottweiler_68.jpg',
 'Rottweiler_70.jpg',
 'Rottweiler_71.jpg',
 'Rottweiler_72.jpg',
 'Rottweiler_73.jpg',
 'Rottweiler_74.jpg',
 'Rottweiler_75.jpg',
 'Rottweiler_76.jpg',
 'Rottweiler_77.jpg',
 'Rottweiler_78.jpg',
 'Rottweiler_79.jpg',
 'Rottweiler_8.jpg',
 'Rottweiler_80.jpg',
 'Rottweiler_81.jpg',
 'Rottweiler_82.jpg',
 'Rottweiler_84.jpg',
 'Rottweiler_85.jpg',
 'Rottweiler_86.jpg',
 'Rottweiler_87.jpg',
 'Rottweiler_88.jpg',
 'Rottweiler_89.jpg',
 'Rottweiler_9.jpg',
 'Rottweiler_91.jpg',
 'Rottweiler_92.jpg',
 'Rottweiler_93.jpg',
 'Rottweiler_94.jpg',
 'Rottweiler_95.jpg',
 'Rottweiler_96.jpg',
 'Rottweiler_97.jpg',
 'Rottweiler_98.jpg',
 'Rottweiler_99.jpg']

In [116]:
len(os.listdir())

89

In [117]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Rottweiler\Rottweiler_5.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [118]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

In [119]:
rottweiler = pd.DataFrame(images)

In [120]:
rottweiler['Breed'] = 'Rottweiler'

In [121]:
len(rottweiler)

89

In [122]:
rottweiler.duplicated().sum()

69

In [123]:
rottweiler = rottweiler.drop_duplicates()

In [124]:
len(rottweiler)

20

In [125]:
rottweiler.duplicated().sum()

0

In [126]:
rottweiler

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,103,160,129,106,163,132,110,169,138,114,...,157,218,198,160,220,199,161,220,200,Rottweiler
1,41,117,58,35,111,50,34,106,45,29,...,3,45,7,4,50,5,27,75,27,Rottweiler
2,59,116,113,64,121,118,70,127,124,74,...,187,239,232,195,241,238,201,241,239,Rottweiler
3,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Rottweiler
4,230,221,218,230,221,219,230,222,219,228,...,97,107,124,97,107,124,98,108,125,Rottweiler
5,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Rottweiler
6,64,92,126,77,105,139,73,104,139,66,...,80,92,116,92,105,131,110,122,150,Rottweiler
7,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Rottweiler
8,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Rottweiler
9,251,249,225,251,249,225,253,249,225,254,...,116,196,148,101,183,132,109,194,140,Rottweiler
11,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Rottweiler
12,23,45,26,51,74,54,74,100,78,48,...,213,226,234,216,228,238,214,229,238,Rottweiler
15,198,230,211,202,235,214,203,239,216,201,...,110,175,134,120,189,148,104,174,133,Rottweiler
16,228,221,218,228,221,218,229,222,219,229,...,67,106,114,67,102,112,73,105,116,Rottweiler
17,187,204,160,194,211,167,199,219,174,200,...,174,197,169,168,189,164,183,201,178,Rottweiler
18,219,203,197,220,204,198,223,207,201,222,...,112,182,146,100,170,134,94,164,128,Rottweiler
19,0,0,0,0,0,0,0,0,0,0,...,141,165,195,142,166,196,148,172,202,Rottweiler
30,36,71,91,36,71,91,37,72,92,38,...,174,190,207,185,201,218,165,181,198,Rottweiler
33,254,254,254,254,254,254,254,254,254,254,...,254,254,254,254,254,254,254,254,254,Rottweiler
51,218,225,204,210,219,198,201,212,195,207,...,124,210,192,132,220,204,131,223,206,Rottweiler

## 10. Yorkshire Terrier

In [127]:
os.chdir(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Yorkshire_Terrier")

In [128]:
os.listdir()

['Yorkshire Terrier_1.jpg',
 'Yorkshire Terrier_10.jpg',
 'Yorkshire Terrier_100.jpg',
 'Yorkshire Terrier_11.jpg',
 'Yorkshire Terrier_12.jpg',
 'Yorkshire Terrier_13.jpg',
 'Yorkshire Terrier_14.jpg',
 'Yorkshire Terrier_15.jpg',
 'Yorkshire Terrier_16.jpg',
 'Yorkshire Terrier_17.jpg',
 'Yorkshire Terrier_18.jpg',
 'Yorkshire Terrier_19.jpg',
 'Yorkshire Terrier_2.jpg',
 'Yorkshire Terrier_20.jpg',
 'Yorkshire Terrier_21.jpg',
 'Yorkshire Terrier_22.jpg',
 'Yorkshire Terrier_23.jpg',
 'Yorkshire Terrier_24.jpg',
 'Yorkshire Terrier_25.jpg',
 'Yorkshire Terrier_26.jpg',
 'Yorkshire Terrier_27.jpg',
 'Yorkshire Terrier_28.jpg',
 'Yorkshire Terrier_29.jpg',
 'Yorkshire Terrier_3.jpg',
 'Yorkshire Terrier_30.jpg',
 'Yorkshire Terrier_31.jpg',
 'Yorkshire Terrier_32.jpg',
 'Yorkshire Terrier_33.jpg',
 'Yorkshire Terrier_34.jpg',
 'Yorkshire Terrier_35.jpg',
 'Yorkshire Terrier_36.jpg',
 'Yorkshire Terrier_37.jpg',
 'Yorkshire Terrier_38.jpg',
 'Yorkshire Terrier_39.jpg',
 'Yorkshire Terrier_4.jpg',
 'Yorkshire Terrier_40.jpg',
 'Yorkshire Terrier_41.jpg',
 'Yorkshire Terrier_42.jpg',
 'Yorkshire Terrier_43.jpg',
 'Yorkshire Terrier_44.jpg',
 'Yorkshire Terrier_45.jpg',
 'Yorkshire Terrier_46.jpg',
 'Yorkshire Terrier_47.jpg',
 'Yorkshire Terrier_48.jpg',
 'Yorkshire Terrier_49.jpg',
 'Yorkshire Terrier_5.jpg',
 'Yorkshire Terrier_50.jpg',
 'Yorkshire Terrier_51.jpg',
 'Yorkshire Terrier_52.jpg',
 'Yorkshire Terrier_53.jpg',
 'Yorkshire Terrier_54.jpg',
 'Yorkshire Terrier_55.jpg',
 'Yorkshire Terrier_56.jpg',
 'Yorkshire Terrier_57.jpg',
 'Yorkshire Terrier_58.jpg',
 'Yorkshire Terrier_59.jpg',
 'Yorkshire Terrier_6.jpg',
 'Yorkshire Terrier_60.jpg',
 'Yorkshire Terrier_61.jpg',
 'Yorkshire Terrier_62.jpg',
 'Yorkshire Terrier_63.jpg',
 'Yorkshire Terrier_64.jpg',
 'Yorkshire Terrier_65.jpg',
 'Yorkshire Terrier_66.jpg',
 'Yorkshire Terrier_67.jpg',
 'Yorkshire Terrier_68.jpg',
 'Yorkshire Terrier_69.jpg',
 'Yorkshire Terrier_7.jpg',
 'Yorkshire Terrier_70.jpg',
 'Yorkshire Terrier_71.jpg',
 'Yorkshire Terrier_72.jpg',
 'Yorkshire Terrier_73.jpg',
 'Yorkshire Terrier_74.jpg',
 'Yorkshire Terrier_75.jpg',
 'Yorkshire Terrier_76.jpg',
 'Yorkshire Terrier_77.jpg',
 'Yorkshire Terrier_78.jpg',
 'Yorkshire Terrier_79.jpg',
 'Yorkshire Terrier_8.jpg',
 'Yorkshire Terrier_80.jpg',
 'Yorkshire Terrier_81.jpg',
 'Yorkshire Terrier_82.jpg',
 'Yorkshire Terrier_83.jpg',
 'Yorkshire Terrier_84.jpg',
 'Yorkshire Terrier_85.jpg',
 'Yorkshire Terrier_86.jpg',
 'Yorkshire Terrier_87.jpg',
 'Yorkshire Terrier_88.jpg',
 'Yorkshire Terrier_89.jpg',
 'Yorkshire Terrier_9.jpg',
 'Yorkshire Terrier_90.jpg',
 'Yorkshire Terrier_91.jpg',
 'Yorkshire Terrier_92.jpg',
 'Yorkshire Terrier_93.jpg',
 'Yorkshire Terrier_94.jpg',
 'Yorkshire Terrier_95.jpg',
 'Yorkshire Terrier_96.jpg',
 'Yorkshire Terrier_97.jpg',
 'Yorkshire Terrier_98.jpg',
 'Yorkshire Terrier_99.jpg']

In [129]:
len(os.listdir())

100

In [133]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Yorkshire_Terrier\Yorkshire Terrier_77.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()

In [131]:
images = []
for image in os.listdir():
    arr = cv2.imread(image)
    res = cv2.resize(arr,(150,150))
    flat = res.flatten()
    images.append(flat)

In [132]:
yt = pd.DataFrame(images)

In [134]:
yt['Breed'] = 'Yorkshire Terrier'

In [135]:
len(yt)

100

In [136]:
yt.duplicated().sum()

79

In [137]:
yt = yt.drop_duplicates()

In [138]:
len(yt)

21

In [139]:
yt.duplicated().sum()

0

In [140]:
yt

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,63,138,140,64,139,141,63,140,142,64,...,127,156,183,116,145,176,118,149,182,Yorkshire Terrier
1,68,68,68,69,69,69,70,70,70,71,...,174,174,174,172,172,172,172,172,172,Yorkshire Terrier
2,3,21,8,4,22,9,4,22,9,5,...,33,58,84,33,58,84,33,58,84,Yorkshire Terrier
3,31,17,19,31,17,18,30,16,18,28,...,213,204,194,212,203,193,212,203,193,Yorkshire Terrier
4,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Yorkshire Terrier
5,75,73,95,74,74,94,72,73,92,69,...,59,159,91,57,160,98,47,153,94,Yorkshire Terrier
6,33,70,60,33,70,60,34,71,61,34,...,36,70,60,36,70,60,36,70,60,Yorkshire Terrier
7,57,101,94,53,97,90,47,91,84,41,...,85,56,43,88,58,42,89,59,40,Yorkshire Terrier
9,0,31,29,1,39,34,6,49,43,7,...,228,196,190,227,194,186,227,191,183,Yorkshire Terrier
10,235,239,240,236,240,241,236,240,241,236,...,206,222,228,208,217,230,208,217,231,Yorkshire Terrier
11,255,255,255,255,255,255,255,255,255,255,...,255,253,253,254,252,252,254,252,252,Yorkshire Terrier
12,190,184,195,195,189,200,200,196,211,208,...,191,200,197,186,196,193,185,196,193,Yorkshire Terrier
13,180,181,179,181,182,180,182,183,181,183,...,103,129,143,94,117,132,87,110,125,Yorkshire Terrier
14,41,66,70,35,62,66,31,58,62,24,...,113,103,125,121,112,138,116,107,134,Yorkshire Terrier
17,57,149,114,58,150,115,59,151,116,60,...,65,158,131,72,163,138,70,161,136,Yorkshire Terrier
18,57,115,140,45,102,128,35,90,117,33,...,61,104,101,54,97,94,47,91,85,Yorkshire Terrier
19,109,161,207,103,155,200,118,169,212,122,...,84,132,118,69,121,112,50,106,98,Yorkshire Terrier
20,72,136,136,72,133,134,73,129,130,75,...,95,133,165,87,124,158,86,123,157,Yorkshire Terrier
21,98,98,255,95,96,255,93,94,255,93,...,77,97,209,77,96,210,76,94,211,Yorkshire Terrier
22,46,78,84,52,86,92,55,89,95,42,...,117,239,232,98,220,212,97,222,212,Yorkshire Terrier
24,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Yorkshire Terrier

## Merging all the DataFrames

In [141]:
Dogs = pd.concat([beagle,boxer,bulldog,dachshund,german,retriever,lab,poodle,rottweiler,yt],axis = 0)

In [142]:
Dogs

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,201,178,186,199,181,188,187,174,180,157,...,147,156,169,143,152,163,145,152,161,Beagle
1,17,41,41,21,45,45,25,51,51,27,...,33,163,152,35,166,155,39,170,159,Beagle
2,157,189,202,157,189,202,157,189,202,157,...,2,20,49,2,19,47,2,19,46,Beagle
3,67,120,117,69,122,119,71,124,121,73,...,74,126,119,52,100,96,36,81,78,Beagle
4,218,226,226,219,227,227,222,231,231,222,...,10,11,15,2,1,10,0,1,11,Beagle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19,109,161,207,103,155,200,118,169,212,122,...,84,132,118,69,121,112,50,106,98,Yorkshire Terrier
20,72,136,136,72,133,134,73,129,130,75,...,95,133,165,87,124,158,86,123,157,Yorkshire Terrier
21,98,98,255,95,96,255,93,94,255,93,...,77,97,209,77,96,210,76,94,211,Yorkshire Terrier
22,46,78,84,52,86,92,55,89,95,42,...,117,239,232,98,220,212,97,222,212,Yorkshire Terrier
24,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Yorkshire Terrier

In [143]:
# Dogs.to_csv('Doggos.csv')

In [144]:
os.getcwd()

'C:\\Users\\Manisha\\DATA SCIENCE\\MACHINE LEARNING\\Dog breeds\\dataset\\Yorkshire_Terrier'

In [145]:
df = pd.read_csv(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Yorkshire_Terrier\Doggos.csv")

In [173]:
df

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,0,201,178,186,199,181,188,187,174,180,...,147,156,169,143,152,163,145,152,161,Beagle
1,1,17,41,41,21,45,45,25,51,51,...,33,163,152,35,166,155,39,170,159,Beagle
2,2,157,189,202,157,189,202,157,189,202,...,2,20,49,2,19,47,2,19,46,Beagle
3,3,67,120,117,69,122,119,71,124,121,...,74,126,119,52,100,96,36,81,78,Beagle
4,4,218,226,226,219,227,227,222,231,231,...,10,11,15,2,1,10,0,1,11,Beagle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,19,109,161,207,103,155,200,118,169,212,...,84,132,118,69,121,112,50,106,98,Yorkshire Terrier
206,20,72,136,136,72,133,134,73,129,130,...,95,133,165,87,124,158,86,123,157,Yorkshire Terrier
207,21,98,98,255,95,96,255,93,94,255,...,77,97,209,77,96,210,76,94,211,Yorkshire Terrier
208,22,46,78,84,52,86,92,55,89,95,...,117,239,232,98,220,212,97,222,212,Yorkshire Terrier
209,24,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Yorkshire Terrier

In [180]:
df = df.drop('Unnamed: 0',axis=1)

In [181]:
df

,0,1,2,3,4,5,6,7,8,9,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
0,201,178,186,199,181,188,187,174,180,157,...,147,156,169,143,152,163,145,152,161,Beagle
1,17,41,41,21,45,45,25,51,51,27,...,33,163,152,35,166,155,39,170,159,Beagle
2,157,189,202,157,189,202,157,189,202,157,...,2,20,49,2,19,47,2,19,46,Beagle
3,67,120,117,69,122,119,71,124,121,73,...,74,126,119,52,100,96,36,81,78,Beagle
4,218,226,226,219,227,227,222,231,231,222,...,10,11,15,2,1,10,0,1,11,Beagle
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
205,109,161,207,103,155,200,118,169,212,122,...,84,132,118,69,121,112,50,106,98,Yorkshire Terrier
206,72,136,136,72,133,134,73,129,130,75,...,95,133,165,87,124,158,86,123,157,Yorkshire Terrier
207,98,98,255,95,96,255,93,94,255,93,...,77,97,209,77,96,210,76,94,211,Yorkshire Terrier
208,46,78,84,52,86,92,55,89,95,42,...,117,239,232,98,220,212,97,222,212,Yorkshire Terrier
209,255,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Yorkshire Terrier

In [4]:
df.iloc[60:90]

,Unnamed: 0,0,1,2,3,4,5,6,7,8,...,67491,67492,67493,67494,67495,67496,67497,67498,67499,Breed
60,21,37,97,66,35,95,65,36,95,67,...,74,86,110,76,91,114,74,93,114,Bulldog
61,22,48,50,61,47,49,60,52,54,65,...,173,167,154,170,164,151,170,164,151,Bulldog
62,24,58,153,133,58,153,133,57,151,134,...,26,66,62,43,79,74,54,88,82,Bulldog
63,59,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Bulldog
64,80,42,84,129,50,92,134,54,88,127,...,92,123,146,89,118,142,85,111,135,Bulldog
65,0,15,37,42,18,43,47,18,43,49,...,103,101,100,100,98,97,100,98,97,Dachshund
66,1,40,53,55,53,66,68,64,77,79,...,182,193,197,168,178,181,170,179,182,Dachshund
67,2,79,118,156,88,127,165,101,140,179,...,96,111,143,104,119,151,105,121,150,Dachshund
68,3,38,58,45,40,60,47,40,63,49,...,64,54,37,59,48,33,58,47,33,Dachshund
69,4,36,89,79,39,92,82,42,96,86,...,94,153,125,85,146,120,85,146,120,Dachshund
70,5,191,186,183,186,181,179,184,179,176,...,179,203,233,181,206,236,182,206,236,Dachshund
71,6,122,202,167,113,193,158,130,212,177,...,87,162,130,89,164,134,96,170,140,Dachshund
72,8,246,255,255,249,255,255,255,254,255,...,254,254,254,255,255,255,255,255,255,Dachshund
73,9,72,91,94,72,91,94,73,92,95,...,56,53,45,50,48,40,50,47,39,Dachshund
74,10,114,168,155,96,150,137,111,165,152,...,102,146,140,126,170,164,103,144,139,Dachshund
75,11,206,199,190,205,198,189,205,198,189,...,83,99,122,103,120,147,70,87,114,Dachshund
76,12,255,249,247,255,251,247,255,249,245,...,135,165,193,138,169,201,123,154,188,Dachshund
77,13,150,157,160,150,157,160,150,157,160,...,57,55,51,109,108,104,198,197,193,Dachshund
78,16,56,57,55,58,59,57,60,61,59,...,26,30,25,28,32,27,28,32,27,Dachshund
79,17,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Dachshund
80,18,149,195,206,149,195,206,150,196,207,...,163,182,185,167,186,189,169,188,191,Dachshund
81,19,255,255,255,255,255,255,255,255,255,...,255,255,255,255,255,255,255,255,255,Dachshund
82,20,142,127,148,143,123,142,141,117,131,...,242,245,249,239,242,246,239,242,246,Dachshund
83,21,16,119,58,9,111,51,9,109,49,...,62,157,100,79,155,97,90,156,97,Dachshund
84,23,72,174,139,92,194,159,88,192,157,...,130,139,138,131,135,140,123,125,133,Dachshund
85,29,189,207,236,186,206,237,187,206,240,...,185,207,242,185,207,242,185,207,242,Dachshund
86,0,185,172,110,178,165,103,183,170,108,...,182,198,205,186,200,206,189,201,207,German Shephard
87,1,181,183,183,177,178,178,178,179,179,...,103,104,102,108,109,107,109,110,108,German Shephard
88,2,70,176,163,70,176,163,71,177,164,...,65,165,155,52,167,145,52,177,149,German Shephard
89,3,0,0,6,0,0,6,0,0,6,...,0,0,0,0,0,0,0,0,0,German Shephard

# Model Creation

### Training the machine

In [182]:
x = df.drop('Breed',axis = 1)
y = df['Breed']

In [21]:
# train_test_split(x,y,test_size=0.2,random_state=22)

[     Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  67490  \
 61           22   48   50   61   47   49   60   52   54   65  ...    157
 18           20   79   80   84   84   85   89   88   89   93  ...     99
 206          20   72  136  136   72  133  134   73  129  130  ...    165
 78           16   56   57   55   58   59   57   60   61   59  ...     26
 204          18   57  115  140   45  102  128   35   90  117  ...     98
 ..          ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...    ...
 100          17  255  255  255  255  255  255  255  255  255  ...    255
 192           3   31   17   19   31   17   18   30   16   18  ...    195
 44            2  255  255  255  255  255  255  255  255  255  ...    255
 132           6  102  230  201  102  230  201  105  232  202  ...     64
 117          11  117  110  101  118  111  102  118  111  102  ...     57

      67491  67492  67493  67494  67495  67496  67497  67498  67499
 61     173    167    154    170    164    151    170    164    151
 18      72    104    102     39     63     62     59     80     78
 206     95    133    165     87    124    158     86    123    157
 78      26     30     25     28     32     27     28     32     27
 204     61    104    101     54     97     94     47     91     85
 ..     ...    ...    ...    ...    ...    ...    ...    ...    ...
 100    255    252    255    255    254    255    255    255    255
 192    213    204    194    212    203    193    212    203    193
 44     255    255    255    255    255    255    255    255    255
 132     34    117     79     19    102     64     26    109     71
 117     11     51     46      5     42     38      6     43     39

 [168 rows x 67501 columns],
      Unnamed: 0    0    1    2    3    4    5    6    7    8  ...  67490  \
 20           22  255  255  255  255  255  255  255  255  255  ...    255
 49            7  255  255  255  255  255  255  255  255  255  ...    255
 114           8  255  255  255  255  255  255  255  255  255  ...    255
 32           12   15   58    7   18   61   10   28   73   25  ...     82
 75           11  206  199  190  205  198  189  205  198  189  ...     98
 171           2   59  116  113   64  121  118   70  127  124  ...    206
 183          17  187  204  160  194  211  167  199  219  174  ...    184
 30           10   29   52   44   29   52   44   29   52   44  ...    108
 91            5  160  229  114  179  246  130  173  235  119  ...    116
 107           0    0   10   18    0   10   18    1   12   20  ...     86
 151           3  120  136  183  120  136  183  120  136  183  ...    243
 119          15  238  210  193  238  210  193  238  210  193  ...    200
 124          20   62  153  168   67  158  173   77  164  180  ...    224
 97           12  255  255  255  255  255  255  255  255  255  ...    255
 95           10  229  213  177  230  214  178  230  214  178  ...    191
 99           14   85   95   59   71   80   50   62   71   50  ...    189
 104          21    9   25   32   10   29   35   16   36   43  ...    223
 41           24  242  255  252  239  253  251  236  250  250  ...    247
 3             3   67  120  117   69  122  119   71  124  121  ...    124
 197           9    0   31   29    1   39   34    6   49   43  ...    191
 46            4  201  217  246  201  217  246  201  217  246  ...    252
 180          12   23   45   26   51   74   54   74  100   78  ...    220
 54           13   10   11   37    8   12   37    0    2   27  ...     81
 98           13  255  197  137  255  198  136  253  199  134  ...     22
 36           18  210  214  232  210  214  232  210  214  232  ...    237
 199          11  255  255  255  255  255  255  255  255  255  ...    252
 152           4  166  209  212  162  205  208  159  202  205  ...     75
 153           5  152  145  128  155  147  130   95   84   70  ...    219
 50            9    0   43  111    0   43  110    0   41  107  ...    132
 156           9   78   95   98   64   83   85   50   70   71  ...    210
 186          30   36   71   91   36   71   91   37   72   92  ...    201
 173           4  230  221  218  230  221  219  230  222  219  ...    123
 164          19   41   45   39   35   40   33   54   59   54  ...     97
 92            6  250  253  255  250  253  255  250  254  255  ...    255
 28            7   29   72   45   27   72   45   25   73   45  ...    247
 12           13  198  192  193  198  192  193  199  193  194  ...     86
 194           5   75   73   95   74   74   94   72   73   92  ...     90
 118          12  246  247  245  245  246  244  242  243  241  ...     94
 110           3  167  176  186  167  176  186  167  176  186  ...    192
 163          18   38  105   83   18   76   55   64  106   88  ...     96
 112           5  255  253  246  255  253  246  255  253  244  ...     60
 176           7  255  255  255  255  255  255  255  255  255  ...    255

      67491  67492  67493  67494  67495  67496  67497  67498  67499
 20     255    255    255    255    255    255    255    255    255
 49     255    255    255    255    255    255    255    255    255
 114    255    255    255    255    255    255    255    255    255
 32      61    160     85     55    156     79     51    154     73
 75      83     99    122    103    120    147     70     87    114
 171    187    239    232    195    241    238    201    241    239
 183    174    197    169    168    189    164    183    201    178
 30      48    101     94     36     85     79     42     89     83
 91      54     84    113     65     98    130     61     93    128
 107     86     95     92     98    107    104    107    116    113
 151    203    213    243    203    213    243    203    213    243
 119     87    174    200     86    173    199     85    172    198
 124    106    211    224    108    214    227    110    214    227
 97     255    255    255    255    255    255    255    255    255
 95     140    168    183    127    156    171    127    158    173
 99     141    173    196    145    177    200    145    177    200
 104     77    209    223     78    206    225     80    205    225
 41     191    228    249    198    237    252    202    242    254
 3       74    126    119     52    100     96     36     81     78
 197    228    196    190    227    194    186    227    191    183
 46     240    246    253    241    247    254    241    247    254
 180    213    226    234    216    228    238    214    229    238
 54      29     35     78     30     34     75     30     35     74
 98      38     78     53     30     74     49     29     76     50
 36     202    208    237    202    208    237    202    208    237
 199    255    253    253    254    252    252    254    252    252
 152    120    119    128    169    166    175    140    137    146
 153    173    208    222    169    206    220    160    197    211
 50      22    110    122     17     98    106      5     83     86
 156    228    214    208    227    213    207    227    213    207
 186    174    190    207    185    201    218    165    181    198
 173     97    107    124     97    107    124     98    108    125
 164     42     96     75     62    112     94     87    136    120
 92     255    255    255    255    255    255    255    255    255
 28     225    241    248    226    240    250    227    239    251
 12      62     71     78     64     76     80     65     77     81
 194     59    159     91     57    160     98     47    153     94
 118    136    145    172     91    100    127     47     56     83
 110    181    186    188    175    181    186    175    181    186
 163     40    139     99     45    138     99     38    129     90
 112     21    121     65     29    130     74     42    143     87
 176    255    255    255    255    255    255    255    255    255

 [42 rows x 67501 columns],
 61                Bulldog
 18                 Beagle
 206     Yorkshire Terrier
 78              Dachshund
 204     Yorkshire Terrier
               ...
 100       German Shephard
 192     Yorkshire Terrier
 44                Bulldog
 132    Labrador Retriever
 117      Golden Retriever
 Name: Breed, Length: 168, dtype: object,
 20                Beagle
 49               Bulldog
 114     Golden Retriever
 32                 Boxer
 75             Dachshund
 171           Rottweiler
 183           Rottweiler
 30                 Boxer
 91       German Shephard
 107     Golden Retriever
 151               Poodle
 119     Golden Retriever
 124     Golden Retriever
 97       German Shephard
 95       German Shephard
 99       German Shephard
 104      German Shephard
 41                 Boxer
 3                 Beagle
 197    Yorkshire Terrier
 46               Bulldog
 180           Rottweiler
 54               Bulldog
 98       German Shephard
 36                 Boxer
 199    Yorkshire Terrier
 152               Poodle
 153               Poodle
 50               Bulldog
 156               Poodle
 186           Rottweiler
 173           Rottweiler
 164               Poodle
 92       German Shephard
 28                 Boxer
 12                Beagle
 194    Yorkshire Terrier
 118     Golden Retriever
 110     Golden Retriever
 163               Poodle
 112     Golden Retriever
 176           Rottweiler
 Name: Breed, dtype: object]

In [183]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=22)

### Testing the Algorithm

#### KNN

In [184]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
accuracy_score(y_test,y_pred)

0.14285714285714285

In [185]:
knn = KNeighborsClassifier()
knn.fit(x_train,y_train)
y_pred = knn.predict(x_test)
f1_score(y_test,y_pred,average='weighted')

0.14625850340136054

#### SVC

In [186]:
svc = SVC()
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)
accuracy_score(y_test,y_pred)

0.11904761904761904

#### Logistic Regression

In [187]:
log = LogisticRegression()
log.fit(x_train,y_train)
y_pred = log.predict(x_test)
accuracy_score(y_test,y_pred)

0.30952380952380953

In [188]:
log = LogisticRegression()
log.fit(x_train,y_train)
y_pred = log.predict(x_test)
precision_score(y_test,y_pred, average = 'weighted',pos_label=1)

0.49263038548752835

In [189]:
log = LogisticRegression()
log.fit(x_train,y_train)
y_pred = log.predict(x_test)
f1_score(y_test,y_pred,average='weighted')

0.33312428312428316

#### Decision Tree

In [190]:
dt = DecisionTreeClassifier()
dt.fit(x_train,y_train)
y_pred = dt.predict(x_test)
accuracy_score(y_test,y_pred)

0.16666666666666666

In [195]:
from sklearn.naive_bayes import GaussianNB

In [196]:
nb = GaussianNB()
nb.fit(x_train,y_train)
y_pred = nb.predict(x_test)
accuracy_score(y_test,y_pred)

0.21428571428571427

## Prediction

In [246]:
image = cv2.imread(r"C:\Users\Manisha\Downloads\GS.jpeg")
cv2.imshow('img',image)
cv2.waitKey(10000)
cv2.destroyAllWindows()
res = cv2.resize(image,(150,150))
flat = res.flatten()
log.predict([flat])[0]

C:\Users\Manisha\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

'German Shephard'

In [161]:
image.shape

(140, 140, 3)

# Pickling

In [202]:
import pickle

In [215]:
pickle.dump(log,open("log.pkl","wb")) # saving the trained model

In [220]:
model = pickle.load(open("log.pkl","rb")) # loading the saved trained model

In [247]:
image = cv2.imread(r"C:\Users\Manisha\DATA SCIENCE\MACHINE LEARNING\Dog breeds\dataset\Dachshund\Dachshund_24.jpg")
cv2.imshow('img',image)
cv2.waitKey(5000)
cv2.destroyAllWindows()
res = cv2.resize(image,(150,150))
flat = res.flatten()
model.predict([flat])[0]

C:\Users\Manisha\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

'Dachshund'

In [221]:
os.getcwd()

'C:\\Users\\Manisha\\DATA SCIENCE\\MACHINE LEARNING\\Dog breeds\\dataset\\Yorkshire_Terrier'